version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: worldforge-mysql
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: worldforge_db
      MYSQL_USER: worldforge_user
      MYSQL_PASSWORD: worldforge_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  backend:
    build:
      context: ./backend


volumes:
  mysql_data:
  jenkins_home:
