version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: worldforge-mysql
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: worldforge_db
      MYSQL_USER: worldforge_user
      MYSQL_PASSWORD: worldforge_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: