# testing register with supabase... requires actual email
POST http://localhost:3001/api/auth/register
content-type: application/json

{
    "email": "email@gmail.com",
    "password": "test"
}

### testing login with supabase
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

