# testing register with supabase... requires actual email
POST http://localhost:3001/api/auth/register
content-type: application/json

{
    "email": "email@gmail.com",
    "password": "testi"
}

### testing login with supabase
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### testing the db connectivity
GET http://localhost:3001/api/auth/test
content-type: application/json


### testing RBAC. user 'test@test.com' has role 'DM'!!!
GET http://localhost:3001/api/auth/testing/0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1MjM1OTcwLCJpYXQiOjE3NDUyMzIzNzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1MjMyMzcwfV0sInNlc3Npb25faWQiOiI2YjlhNGU1YS0xMjE1LTQ2ZGMtYTM0YS1jZmVlN2Y0YWY1NDYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.bRY7tQxeo2OWG_XHEuOAFek5WjebLmbi8k18qGD_OlA

### testing getting user campaign role data
GET http://localhost:3001/api/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk3NzY0LCJpYXQiOjE3NDU3OTQxNjQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk0MTY0fV0sInNlc3Npb25faWQiOiI3OTBiYzFhNC02OWVhLTQ1OTctOGU5OS0xN2RmYjZhOWIyZWIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.aBg8KEZsf0vcL9bph9-_9CpOoE-Avqsx1LLcKnVEUu0

### testing getting specific user's info
GET http://localhost:3001/api/users/6bb63985-2218-4f1c-8049-4c3a976a7aa5

### testing getting notifications for user
GET http://localhost:3001/api/users/notifications
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk4NjY2LCJpYXQiOjE3NDU3OTUwNjYsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk1MDY2fV0sInNlc3Npb25faWQiOiIxN2QzZGIxMC00YjI2LTRmZTgtODlhMC0wYWNmZDUxODA5YmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.rYlQCs5jaZDydRk9_ekKx6mJkcyWEmu8XU6rgspuy6Q

### testing getting world events for user worlds
GET http://localhost:3001/api/users/events
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk4NjY2LCJpYXQiOjE3NDU3OTUwNjYsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk1MDY2fV0sInNlc3Npb25faWQiOiIxN2QzZGIxMC00YjI2LTRmZTgtODlhMC0wYWNmZDUxODA5YmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.rYlQCs5jaZDydRk9_ekKx6mJkcyWEmu8XU6rgspuy6Q

