# testing register with supabase... requires actual email
POST http://localhost:3001/api/auth/register
content-type: application/json

{
    "email": "email@gmail.com",
    "password": "testi"
}

### testing login with supabase
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### testing the db connectivity
GET http://localhost:3001/api/auth/test
content-type: application/json


### testing RBAC. user 'test@test.com' has role 'DM'!!!
GET http://localhost:3001/api/auth/testing/0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1MjM1OTcwLCJpYXQiOjE3NDUyMzIzNzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1MjMyMzcwfV0sInNlc3Npb25faWQiOiI2YjlhNGU1YS0xMjE1LTQ2ZGMtYTM0YS1jZmVlN2Y0YWY1NDYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.bRY7tQxeo2OWG_XHEuOAFek5WjebLmbi8k18qGD_OlA

### testing getting user campaign role data
GET http://localhost:3001/api/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk3NzY0LCJpYXQiOjE3NDU3OTQxNjQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk0MTY0fV0sInNlc3Npb25faWQiOiI3OTBiYzFhNC02OWVhLTQ1OTctOGU5OS0xN2RmYjZhOWIyZWIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.aBg8KEZsf0vcL9bph9-_9CpOoE-Avqsx1LLcKnVEUu0

### testing getting specific user's info
GET http://localhost:3001/api/users/6bb63985-2218-4f1c-8049-4c3a976a7aa5

### testing getting notifications for user
GET http://localhost:3001/api/users/notifications
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk4NjY2LCJpYXQiOjE3NDU3OTUwNjYsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk1MDY2fV0sInNlc3Npb25faWQiOiIxN2QzZGIxMC00YjI2LTRmZTgtODlhMC0wYWNmZDUxODA5YmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.rYlQCs5jaZDydRk9_ekKx6mJkcyWEmu8XU6rgspuy6Q

### testing getting world events for user worlds
GET http://localhost:3001/api/users/events
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1Nzk4NjY2LCJpYXQiOjE3NDU3OTUwNjYsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1Nzk1MDY2fV0sInNlc3Npb25faWQiOiIxN2QzZGIxMC00YjI2LTRmZTgtODlhMC0wYWNmZDUxODA5YmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.rYlQCs5jaZDydRk9_ekKx6mJkcyWEmu8XU6rgspuy6Q

### testing new world creation
POST http://localhost:3000/api/worlds/create_world
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2NTE5ODMzLCJpYXQiOjE3NDY1MTYyMzMsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ2NTE2MjMzfV0sInNlc3Npb25faWQiOiIzMjJhNjI2NC0zYTcxLTRmYWMtYWU1MS1jZWNhMTBhY2VjM2EiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.hKhOJH-2cMq8LLH7Ab2qFn7BQcK8SyN2Id6SIvic2sg

{
    "name": "World Settings Test 2",
    "description": "Will there be settings attached to this?"
}

### test world name change
POST http://localhost:3000/api/worlds/update_world_name
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MDM0NTA0LCJpYXQiOjE3NDcwMzA5MDQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3MDMwOTA0fV0sInNlc3Npb25faWQiOiI1YjA2NDNhMC02NjA4LTQwYzEtYjkwZC02NmE5OTFmNWU5YTYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.1JH3DLbvDBPx0B2mhA2aVs-A3Pd9rz5PPOsb2qqJe44

{
    "id": "4",
    "input": "Did the name change?"
}

### test world description change
POST http://localhost:3000/api/worlds/update_world_description
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MDM0NTA0LCJpYXQiOjE3NDcwMzA5MDQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3MDMwOTA0fV0sInNlc3Npb25faWQiOiI1YjA2NDNhMC02NjA4LTQwYzEtYjkwZC02NmE5OTFmNWU5YTYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.1JH3DLbvDBPx0B2mhA2aVs-A3Pd9rz5PPOsb2qqJe44

{
    "id": "4",
    "input": "Did the description change?"
}

### testing get world
GET http://localhost:3000/api/worlds/get_world
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTgzNTMwLCJpYXQiOjE3NDY5Nzk5MzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ2OTc5OTMwfV0sInNlc3Npb25faWQiOiJiYmQ3YjBiYS05ZDhkLTQ1ZDUtODZlNi0zYzVlYmZmOGNlZjMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.fmK7Xy4w9kF-6fLAv2vVb4MyYX-wsFLHOKOCyHWVl1E

{
    "search": 3
}

### test delete world
DELETE http://localhost:3000/api/worlds/delete_world
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3Mjc5Mjk4LCJpYXQiOjE3NDcyNzU2OTgsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3Mjc1Njk4fV0sInNlc3Npb25faWQiOiI3ZWU5NGVlMS01ZDBlLTQzOGUtYTc2MS1iMjEzYTYyNmNjYWYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oxSMpsh2rQD3PTuHwApmGqVFDBgwZ5c6A9mXSDQZWpk

{
    "search": 5
}

### testing change
POST http://localhost:3000/api/worlds/update_world_settings
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MDI4NDgzLCJpYXQiOjE3NDcwMjQ4ODMsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3MDI0ODgzfV0sInNlc3Npb25faWQiOiIyNWMxNTA1ZC1iZTE3LTQ1ZjQtOGNmNC1jNzgzNGE5NTc1ZWYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.kcGPH-KbmcWjR3IUT7URxm5rLtQ9VsEfelgbQP_vaGI

{
    "settings_id": 1,
    "settings": {
        "allow_public_visibility": true, 
        "join_method": "invite",
        "max_campaigns": 7,
        "allow_dm_invites": false,
        "enable_fog_of_war": true,
        "inter_party_visibility": true,
        "spectator_map_visibility": false,
        "show_party_position_globally": false
    }
}

### testing create new world time
POST http://localhost:3000/api/worlds/create_world_time
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3Mjc5Mjk4LCJpYXQiOjE3NDcyNzU2OTgsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3Mjc1Njk4fV0sInNlc3Npb25faWQiOiI3ZWU5NGVlMS01ZDBlLTQzOGUtYTc2MS1iMjEzYTYyNmNjYWYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oxSMpsh2rQD3PTuHwApmGqVFDBgwZ5c6A9mXSDQZWpk

{
    "search": 5
}

### testing change world time
POST http://localhost:3000/api/worlds/update_world_time
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MTIzMjMwLCJpYXQiOjE3NDcxMTk2MzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3MTE5NjMwfV0sInNlc3Npb25faWQiOiIzNTkyZjM3ZC05NmNlLTQ5OTgtYWJmNC00OTNmNGVmZDIxNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.IWOci8W-9912xI0cM_LZSNuywKeJEXEFWVvqo5-8uSI

{
    "id": "1",
    "input": "Franktuber 72nd, 812"
}

### test delete world time
DELETE http://localhost:3000/api/worlds/delete_world_time
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3Mjc5Mjk4LCJpYXQiOjE3NDcyNzU2OTgsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3Mjc1Njk4fV0sInNlc3Npb25faWQiOiI3ZWU5NGVlMS01ZDBlLTQzOGUtYTc2MS1iMjEzYTYyNmNjYWYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oxSMpsh2rQD3PTuHwApmGqVFDBgwZ5c6A9mXSDQZWpk

{
    "search": 3
}

### testing create world event
POST http://localhost:3000/api/events/create_event
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImFqM29NWnVRc3ZoaEhjVGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3dhYWlxand2amN0ZmFndXhtZ2ZqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2YmI2Mzk4NS0yMjE4LTRmMWMtODA0OS00YzNhOTc2YTdhYTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MTIzMjMwLCJpYXQiOjE3NDcxMTk2MzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ3MTE5NjMwfV0sInNlc3Npb25faWQiOiIzNTkyZjM3ZC05NmNlLTQ5OTgtYWJmNC00OTNmNGVmZDIxNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.IWOci8W-9912xI0cM_LZSNuywKeJEXEFWVvqo5-8uSI

{
    "id": 4,
    "title": "NEW EVENT!",
    "description": "the event of all time",
    "visible_at_session": "4"
}
